#!/bin/bash
set -e

while true; do
  # 发送请求，-i 输出头和体，-s 静默模式
  RESPONSE=$(curl -i -s "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

  # 把响应头和体分离：
  # 先取请求 ID （从响应头中）
  REQUEST_ID=$(echo "$RESPONSE" | awk /lambda-runtime-aws-request-id/{print } | tr -d $r)

  # 这里处理 EVENT，比如打印或者传给程序
  echo "RequestId: $REQUEST_ID"
  RESULT=$(echo "$RESPONSE" | ./zrlog)

  # 回复 Lambda 运行环境，示例返回事件原文
  curl -s -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/${REQUEST_ID}/response" \
    -d "${RESULT}"
done
