#This is a database configuration dbFile
#Sat Jun 14 19:24:21 CST 2025
driverClass=com.mysql.cj.jdbc.Driver
jdbcUrl=jdbc\:mysql\://192.168.201.4\:3306/zrlog_test?characterEncoding\=UTF-8&allowPublicKeyRetrieval\=true&useSSL\=false&serverTimezone\=GMT
password=123456
user=zrlog_test
