name: ZrLog package
on:
  push:
    branches:
      - release
jobs:
  build:
    name: ZrLog package ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: |
          mkdir -p /var/lib/jenkins/download
          bash -e bin/build-final-package.sh release 正式版本 /var/lib/jenkins/download
          bash shell/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /var/lib/jenkins/download