name: build preview jar
on:
  push:
    branches:
      - master
jobs:
  build:
    name: ZrLog package ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        architecture: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules admin
        uses: actions/cache@v3
        with:
          path: admin-web/src/main/frontend/node_modules
          key: ${{ runner.os }}-node-admin-${{ hashFiles('admin-web/src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-admin-
      - name: Cache node modules blog
        uses: actions/cache@v3
        with:
          path: blog-web/src/main/frontend/node_modules
          key: ${{ runner.os }}-node-blog-${{ hashFiles('blog-web/src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-blog-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: |
          mkdir -p /tmp/download
          bash -e bin/build-final-package.sh preview 预览版 /tmp/download
          bash bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download preview