name: build native preview package
on:
  push:
    branches:
      - master
jobs:
  build:
    name: ZrLog on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: deploy-preview-on-${{ matrix.os }}-native   # 同一个 group 的任务会排队执行
      cancel-in-progress: false # 不取消前一个任务，而是等待
    strategy:
      matrix:
        os: [ ubuntu-22.04,ubuntu-24.04-arm,macos-13,macos-14,windows-2022 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and upload binary
        run: |
          mkdir -p /tmp/download
          bash -e shell/native/build-final-native.sh preview /tmp/download zip
          bash -e shell/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download preview ${{ secrets.HOST }}