name: build on Linux amd64 preview native
on:
  push:
    branches:
      - master
jobs:
  build:
    name: ZrLog on ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        architecture: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and upload binary
        run: |
          mkdir -p /tmp/download
          bash -e bin/build-final-native.sh preview 预览版 /tmp/download ubuntu
          bash -e bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download preview